# Generated by Django 4.1.7 on 2023-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_store', '0004_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
